# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui',
# licensing of 'mainui.ui' applies.
#
# Created: Sun Apr 26 20:37:26 2020
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 712)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 141, 17))
        self.label_2.setObjectName("label_2")
        self.pBCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pBCalculate.setGeometry(QtCore.QRect(50, 610, 131, 41))
        self.pBCalculate.setObjectName("pBCalculate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(62, 30, 48, 19))
        self.label.setObjectName("label")
        self.lew1w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew1w3.setGeometry(QtCore.QRect(350, 31, 100, 29))
        self.lew1w3.setMaxLength(2)
        self.lew1w3.setObjectName("lew1w3")
        self.lew1w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew1w1.setGeometry(QtCore.QRect(120, 31, 100, 29))
        self.lew1w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew1w1.setMaxLength(2)
        self.lew1w1.setObjectName("lew1w1")
        self.lew1w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew1w2.setGeometry(QtCore.QRect(230, 31, 100, 29))
        self.lew1w2.setMaxLength(2)
        self.lew1w2.setObjectName("lew1w2")
        self.labelWort1 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort1.setGeometry(QtCore.QRect(517, 31, 103, 19))
        self.labelWort1.setObjectName("labelWort1")
        self.labelWort1Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort1Index.setGeometry(QtCore.QRect(471, 31, 40, 19))
        self.labelWort1Index.setObjectName("labelWort1Index")
        self.labelWort2Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort2Index.setGeometry(QtCore.QRect(471, 71, 40, 19))
        self.labelWort2Index.setObjectName("labelWort2Index")
        self.lew2w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew2w3.setGeometry(QtCore.QRect(350, 71, 100, 29))
        self.lew2w3.setMaxLength(2)
        self.lew2w3.setObjectName("lew2w3")
        self.lew2w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew2w1.setGeometry(QtCore.QRect(120, 71, 100, 29))
        self.lew2w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew2w1.setMaxLength(2)
        self.lew2w1.setObjectName("lew2w1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(61, 71, 48, 19))
        self.label_3.setObjectName("label_3")
        self.labelWort2 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort2.setGeometry(QtCore.QRect(517, 71, 103, 19))
        self.labelWort2.setObjectName("labelWort2")
        self.lew2w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew2w2.setGeometry(QtCore.QRect(230, 71, 100, 29))
        self.lew2w2.setMaxLength(2)
        self.lew2w2.setObjectName("lew2w2")
        self.labelWort3 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort3.setGeometry(QtCore.QRect(517, 111, 103, 19))
        self.labelWort3.setObjectName("labelWort3")
        self.lew3w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew3w2.setGeometry(QtCore.QRect(230, 111, 100, 29))
        self.lew3w2.setMaxLength(2)
        self.lew3w2.setObjectName("lew3w2")
        self.lew3w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew3w3.setGeometry(QtCore.QRect(350, 111, 100, 29))
        self.lew3w3.setMaxLength(2)
        self.lew3w3.setObjectName("lew3w3")
        self.lew3w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew3w1.setGeometry(QtCore.QRect(120, 111, 100, 29))
        self.lew3w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew3w1.setMaxLength(2)
        self.lew3w1.setObjectName("lew3w1")
        self.labelWort3Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort3Index.setGeometry(QtCore.QRect(471, 111, 40, 19))
        self.labelWort3Index.setObjectName("labelWort3Index")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(61, 111, 48, 19))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(61, 431, 55, 19))
        self.label_9.setObjectName("label_9")
        self.lew11w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew11w3.setGeometry(QtCore.QRect(350, 431, 100, 29))
        self.lew11w3.setMaxLength(2)
        self.lew11w3.setObjectName("lew11w3")
        self.lew11w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew11w1.setGeometry(QtCore.QRect(120, 431, 100, 29))
        self.lew11w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew11w1.setMaxLength(2)
        self.lew11w1.setObjectName("lew11w1")
        self.lew11w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew11w2.setGeometry(QtCore.QRect(230, 431, 100, 29))
        self.lew11w2.setMaxLength(2)
        self.lew11w2.setObjectName("lew11w2")
        self.labelWort11Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort11Index.setGeometry(QtCore.QRect(471, 431, 40, 19))
        self.labelWort11Index.setObjectName("labelWort11Index")
        self.labelWort11 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort11.setGeometry(QtCore.QRect(517, 431, 103, 19))
        self.labelWort11.setObjectName("labelWort11")
        self.labelWort6 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort6.setGeometry(QtCore.QRect(517, 231, 103, 19))
        self.labelWort6.setObjectName("labelWort6")
        self.lew6w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew6w3.setGeometry(QtCore.QRect(350, 231, 100, 29))
        self.lew6w3.setMaxLength(2)
        self.lew6w3.setObjectName("lew6w3")
        self.lew6w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew6w1.setGeometry(QtCore.QRect(120, 231, 100, 29))
        self.lew6w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew6w1.setMaxLength(2)
        self.lew6w1.setObjectName("lew6w1")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(61, 231, 48, 19))
        self.label_5.setObjectName("label_5")
        self.labelWort6Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort6Index.setGeometry(QtCore.QRect(471, 231, 40, 19))
        self.labelWort6Index.setObjectName("labelWort6Index")
        self.lew6w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew6w2.setGeometry(QtCore.QRect(230, 231, 100, 29))
        self.lew6w2.setMaxLength(2)
        self.lew6w2.setObjectName("lew6w2")
        self.labelWort10 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort10.setGeometry(QtCore.QRect(517, 391, 103, 19))
        self.labelWort10.setObjectName("labelWort10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(61, 391, 56, 19))
        self.label_13.setObjectName("label_13")
        self.lew10w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew10w3.setGeometry(QtCore.QRect(350, 391, 100, 29))
        self.lew10w3.setMaxLength(2)
        self.lew10w3.setObjectName("lew10w3")
        self.lew10w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew10w1.setGeometry(QtCore.QRect(120, 390, 100, 29))
        self.lew10w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew10w1.setMaxLength(2)
        self.lew10w1.setObjectName("lew10w1")
        self.lew10w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew10w2.setGeometry(QtCore.QRect(230, 391, 100, 29))
        self.lew10w2.setMaxLength(2)
        self.lew10w2.setObjectName("lew10w2")
        self.labelWort10Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort10Index.setGeometry(QtCore.QRect(471, 391, 40, 19))
        self.labelWort10Index.setObjectName("labelWort10Index")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(61, 311, 48, 19))
        self.label_10.setObjectName("label_10")
        self.lew8w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew8w3.setGeometry(QtCore.QRect(350, 311, 100, 29))
        self.lew8w3.setMaxLength(2)
        self.lew8w3.setObjectName("lew8w3")
        self.lew8w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew8w1.setGeometry(QtCore.QRect(120, 311, 100, 29))
        self.lew8w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew8w1.setMaxLength(2)
        self.lew8w1.setObjectName("lew8w1")
        self.lew8w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew8w2.setGeometry(QtCore.QRect(230, 311, 100, 29))
        self.lew8w2.setMaxLength(2)
        self.lew8w2.setObjectName("lew8w2")
        self.labelWort8Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort8Index.setGeometry(QtCore.QRect(471, 311, 40, 19))
        self.labelWort8Index.setObjectName("labelWort8Index")
        self.labelWort8 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort8.setGeometry(QtCore.QRect(517, 311, 103, 19))
        self.labelWort8.setObjectName("labelWort8")
        self.labelWort4Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort4Index.setGeometry(QtCore.QRect(471, 151, 40, 19))
        self.labelWort4Index.setObjectName("labelWort4Index")
        self.labelWort4 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort4.setGeometry(QtCore.QRect(517, 151, 103, 19))
        self.labelWort4.setObjectName("labelWort4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(61, 151, 48, 19))
        self.label_7.setObjectName("label_7")
        self.lew4w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew4w3.setGeometry(QtCore.QRect(350, 151, 100, 29))
        self.lew4w3.setMaxLength(2)
        self.lew4w3.setObjectName("lew4w3")
        self.lew4w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew4w1.setGeometry(QtCore.QRect(120, 151, 100, 29))
        self.lew4w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew4w1.setMaxLength(2)
        self.lew4w1.setObjectName("lew4w1")
        self.lew4w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew4w2.setGeometry(QtCore.QRect(230, 151, 100, 29))
        self.lew4w2.setMaxLength(2)
        self.lew4w2.setObjectName("lew4w2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(61, 191, 48, 19))
        self.label_6.setObjectName("label_6")
        self.lew5w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew5w3.setGeometry(QtCore.QRect(350, 191, 100, 29))
        self.lew5w3.setMaxLength(2)
        self.lew5w3.setObjectName("lew5w3")
        self.lew5w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew5w1.setGeometry(QtCore.QRect(120, 191, 100, 29))
        self.lew5w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew5w1.setMaxLength(2)
        self.lew5w1.setObjectName("lew5w1")
        self.labelWort5 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort5.setGeometry(QtCore.QRect(517, 191, 103, 19))
        self.labelWort5.setObjectName("labelWort5")
        self.lew5w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew5w2.setGeometry(QtCore.QRect(230, 191, 100, 29))
        self.lew5w2.setMaxLength(2)
        self.lew5w2.setObjectName("lew5w2")
        self.labelWort5Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort5Index.setGeometry(QtCore.QRect(471, 191, 40, 19))
        self.labelWort5Index.setObjectName("labelWort5Index")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(61, 471, 56, 19))
        self.label_11.setObjectName("label_11")
        self.lew12w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew12w3.setGeometry(QtCore.QRect(350, 471, 100, 29))
        self.lew12w3.setMaxLength(2)
        self.lew12w3.setObjectName("lew12w3")
        self.lew12w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew12w1.setGeometry(QtCore.QRect(120, 471, 100, 29))
        self.lew12w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew12w1.setMaxLength(2)
        self.lew12w1.setObjectName("lew12w1")
        self.lew12w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew12w2.setGeometry(QtCore.QRect(230, 471, 100, 29))
        self.lew12w2.setMaxLength(2)
        self.lew12w2.setObjectName("lew12w2")
        self.labelWort12Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort12Index.setGeometry(QtCore.QRect(471, 471, 40, 19))
        self.labelWort12Index.setObjectName("labelWort12Index")
        self.labelWort12 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort12.setGeometry(QtCore.QRect(517, 471, 103, 19))
        self.labelWort12.setObjectName("labelWort12")
        self.labelWort9Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort9Index.setGeometry(QtCore.QRect(471, 351, 40, 19))
        self.labelWort9Index.setObjectName("labelWort9Index")
        self.labelWort9 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort9.setGeometry(QtCore.QRect(517, 351, 103, 19))
        self.labelWort9.setObjectName("labelWort9")
        self.lew9w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew9w3.setGeometry(QtCore.QRect(350, 351, 100, 29))
        self.lew9w3.setMaxLength(2)
        self.lew9w3.setObjectName("lew9w3")
        self.lew9w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew9w1.setGeometry(QtCore.QRect(120, 351, 100, 29))
        self.lew9w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew9w1.setMaxLength(2)
        self.lew9w1.setObjectName("lew9w1")
        self.lew9w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew9w2.setGeometry(QtCore.QRect(230, 351, 100, 29))
        self.lew9w2.setMaxLength(2)
        self.lew9w2.setObjectName("lew9w2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(61, 351, 48, 19))
        self.label_8.setObjectName("label_8")
        self.lew7w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew7w2.setGeometry(QtCore.QRect(230, 271, 100, 29))
        self.lew7w2.setMaxLength(2)
        self.lew7w2.setObjectName("lew7w2")
        self.labelWort7Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort7Index.setGeometry(QtCore.QRect(471, 271, 40, 19))
        self.labelWort7Index.setObjectName("labelWort7Index")
        self.labelWort7 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort7.setGeometry(QtCore.QRect(517, 271, 103, 19))
        self.labelWort7.setObjectName("labelWort7")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(61, 271, 48, 19))
        self.label_12.setObjectName("label_12")
        self.lew7w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew7w3.setGeometry(QtCore.QRect(350, 271, 100, 29))
        self.lew7w3.setMaxLength(2)
        self.lew7w3.setObjectName("lew7w3")
        self.lew7w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew7w1.setGeometry(QtCore.QRect(120, 271, 100, 29))
        self.lew7w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew7w1.setMaxLength(2)
        self.lew7w1.setObjectName("lew7w1")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(60, 520, 56, 19))
        self.label_26.setObjectName("label_26")
        self.pBClear = QtWidgets.QPushButton(self.centralwidget)
        self.pBClear.setGeometry(QtCore.QRect(210, 610, 131, 41))
        self.pBClear.setObjectName("pBClear")
        self.labelWort24 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort24.setGeometry(QtCore.QRect(1097, 471, 103, 19))
        self.labelWort24.setObjectName("labelWort24")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(641, 471, 61, 19))
        self.label_20.setObjectName("label_20")
        self.labelWort24Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort24Index.setGeometry(QtCore.QRect(1051, 471, 40, 19))
        self.labelWort24Index.setObjectName("labelWort24Index")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(641, 31, 56, 19))
        self.label_14.setObjectName("label_14")
        self.lew13w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew13w3.setGeometry(QtCore.QRect(935, 31, 110, 29))
        self.lew13w3.setMaxLength(2)
        self.lew13w3.setObjectName("lew13w3")
        self.lew13w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew13w1.setGeometry(QtCore.QRect(703, 31, 110, 29))
        self.lew13w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew13w1.setMaxLength(2)
        self.lew13w1.setObjectName("lew13w1")
        self.lew13w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew13w2.setGeometry(QtCore.QRect(819, 31, 110, 29))
        self.lew13w2.setMaxLength(2)
        self.lew13w2.setObjectName("lew13w2")
        self.labelWort13Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort13Index.setGeometry(QtCore.QRect(1051, 31, 40, 19))
        self.labelWort13Index.setObjectName("labelWort13Index")
        self.labelWort13 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort13.setGeometry(QtCore.QRect(1097, 31, 103, 19))
        self.labelWort13.setObjectName("labelWort13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(641, 111, 56, 19))
        self.label_15.setObjectName("label_15")
        self.lew15w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew15w3.setGeometry(QtCore.QRect(935, 111, 110, 29))
        self.lew15w3.setMaxLength(2)
        self.lew15w3.setObjectName("lew15w3")
        self.lew15w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew15w1.setGeometry(QtCore.QRect(703, 111, 110, 29))
        self.lew15w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew15w1.setMaxLength(2)
        self.lew15w1.setObjectName("lew15w1")
        self.lew15w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew15w2.setGeometry(QtCore.QRect(819, 111, 110, 29))
        self.lew15w2.setMaxLength(2)
        self.lew15w2.setObjectName("lew15w2")
        self.labelWort15Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort15Index.setGeometry(QtCore.QRect(1051, 111, 40, 19))
        self.labelWort15Index.setObjectName("labelWort15Index")
        self.labelWort15 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort15.setGeometry(QtCore.QRect(1097, 111, 103, 19))
        self.labelWort15.setObjectName("labelWort15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(641, 151, 56, 19))
        self.label_16.setObjectName("label_16")
        self.lew16w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew16w3.setGeometry(QtCore.QRect(935, 151, 110, 29))
        self.lew16w3.setMaxLength(2)
        self.lew16w3.setObjectName("lew16w3")
        self.lew16w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew16w1.setGeometry(QtCore.QRect(703, 151, 110, 29))
        self.lew16w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew16w1.setMaxLength(2)
        self.lew16w1.setObjectName("lew16w1")
        self.lew16w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew16w2.setGeometry(QtCore.QRect(819, 151, 110, 29))
        self.lew16w2.setMaxLength(2)
        self.lew16w2.setObjectName("lew16w2")
        self.labelWort16Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort16Index.setGeometry(QtCore.QRect(1051, 151, 40, 19))
        self.labelWort16Index.setObjectName("labelWort16Index")
        self.labelWort16 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort16.setGeometry(QtCore.QRect(1097, 151, 103, 19))
        self.labelWort16.setObjectName("labelWort16")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(641, 391, 56, 19))
        self.label_19.setObjectName("label_19")
        self.lew22w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew22w3.setGeometry(QtCore.QRect(935, 391, 110, 29))
        self.lew22w3.setMaxLength(2)
        self.lew22w3.setObjectName("lew22w3")
        self.lew22w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew22w1.setGeometry(QtCore.QRect(703, 391, 110, 29))
        self.lew22w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew22w1.setMaxLength(2)
        self.lew22w1.setObjectName("lew22w1")
        self.lew22w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew22w2.setGeometry(QtCore.QRect(819, 391, 110, 29))
        self.lew22w2.setMaxLength(2)
        self.lew22w2.setObjectName("lew22w2")
        self.labelWort22Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort22Index.setGeometry(QtCore.QRect(1051, 391, 40, 19))
        self.labelWort22Index.setObjectName("labelWort22Index")
        self.labelWort22 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort22.setGeometry(QtCore.QRect(1097, 391, 103, 19))
        self.labelWort22.setObjectName("labelWort22")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(641, 351, 56, 19))
        self.label_17.setObjectName("label_17")
        self.lew21w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew21w3.setGeometry(QtCore.QRect(935, 351, 110, 29))
        self.lew21w3.setMaxLength(2)
        self.lew21w3.setObjectName("lew21w3")
        self.lew21w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew21w1.setGeometry(QtCore.QRect(703, 351, 110, 29))
        self.lew21w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew21w1.setMaxLength(2)
        self.lew21w1.setObjectName("lew21w1")
        self.lew21w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew21w2.setGeometry(QtCore.QRect(819, 351, 110, 29))
        self.lew21w2.setMaxLength(2)
        self.lew21w2.setObjectName("lew21w2")
        self.labelWort21Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort21Index.setGeometry(QtCore.QRect(1051, 351, 40, 19))
        self.labelWort21Index.setObjectName("labelWort21Index")
        self.labelWort21 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort21.setGeometry(QtCore.QRect(1097, 351, 103, 19))
        self.labelWort21.setObjectName("labelWort21")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(641, 311, 56, 19))
        self.label_18.setObjectName("label_18")
        self.lew20w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew20w3.setGeometry(QtCore.QRect(935, 311, 110, 29))
        self.lew20w3.setMaxLength(2)
        self.lew20w3.setObjectName("lew20w3")
        self.lew20w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew20w1.setGeometry(QtCore.QRect(703, 311, 110, 29))
        self.lew20w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew20w1.setMaxLength(2)
        self.lew20w1.setObjectName("lew20w1")
        self.lew20w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew20w2.setGeometry(QtCore.QRect(819, 311, 110, 29))
        self.lew20w2.setMaxLength(2)
        self.lew20w2.setObjectName("lew20w2")
        self.labelWort20Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort20Index.setGeometry(QtCore.QRect(1051, 311, 40, 19))
        self.labelWort20Index.setObjectName("labelWort20Index")
        self.labelWort20 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort20.setGeometry(QtCore.QRect(1097, 311, 103, 19))
        self.labelWort20.setObjectName("labelWort20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(641, 191, 56, 19))
        self.label_21.setObjectName("label_21")
        self.lew17w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew17w3.setGeometry(QtCore.QRect(935, 191, 110, 29))
        self.lew17w3.setMaxLength(2)
        self.lew17w3.setObjectName("lew17w3")
        self.lew17w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew17w1.setGeometry(QtCore.QRect(703, 191, 110, 29))
        self.lew17w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew17w1.setMaxLength(2)
        self.lew17w1.setObjectName("lew17w1")
        self.lew17w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew17w2.setGeometry(QtCore.QRect(819, 191, 110, 29))
        self.lew17w2.setMaxLength(2)
        self.lew17w2.setObjectName("lew17w2")
        self.labelWort17Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort17Index.setGeometry(QtCore.QRect(1051, 191, 40, 19))
        self.labelWort17Index.setObjectName("labelWort17Index")
        self.labelWort17 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort17.setGeometry(QtCore.QRect(1097, 191, 103, 19))
        self.labelWort17.setObjectName("labelWort17")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(641, 231, 56, 19))
        self.label_22.setObjectName("label_22")
        self.lew18w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew18w3.setGeometry(QtCore.QRect(935, 231, 110, 29))
        self.lew18w3.setMaxLength(2)
        self.lew18w3.setObjectName("lew18w3")
        self.lew18w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew18w1.setGeometry(QtCore.QRect(703, 231, 110, 29))
        self.lew18w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew18w1.setMaxLength(2)
        self.lew18w1.setObjectName("lew18w1")
        self.lew18w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew18w2.setGeometry(QtCore.QRect(819, 231, 110, 29))
        self.lew18w2.setMaxLength(2)
        self.lew18w2.setObjectName("lew18w2")
        self.labelWort18Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort18Index.setGeometry(QtCore.QRect(1051, 231, 40, 19))
        self.labelWort18Index.setObjectName("labelWort18Index")
        self.labelWort18 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort18.setGeometry(QtCore.QRect(1097, 231, 103, 19))
        self.labelWort18.setObjectName("labelWort18")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(641, 271, 56, 19))
        self.label_23.setObjectName("label_23")
        self.lew19w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew19w3.setGeometry(QtCore.QRect(935, 271, 110, 29))
        self.lew19w3.setMaxLength(2)
        self.lew19w3.setObjectName("lew19w3")
        self.lew19w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew19w1.setGeometry(QtCore.QRect(703, 271, 110, 29))
        self.lew19w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew19w1.setMaxLength(2)
        self.lew19w1.setObjectName("lew19w1")
        self.lew19w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew19w2.setGeometry(QtCore.QRect(819, 271, 110, 29))
        self.lew19w2.setMaxLength(2)
        self.lew19w2.setObjectName("lew19w2")
        self.labelWort19Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort19Index.setGeometry(QtCore.QRect(1051, 271, 40, 19))
        self.labelWort19Index.setObjectName("labelWort19Index")
        self.labelWort19 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort19.setGeometry(QtCore.QRect(1097, 271, 103, 19))
        self.labelWort19.setObjectName("labelWort19")
        self.lew23w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew23w2.setGeometry(QtCore.QRect(819, 431, 110, 29))
        self.lew23w2.setMaxLength(2)
        self.lew23w2.setObjectName("lew23w2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(641, 431, 56, 19))
        self.label_24.setObjectName("label_24")
        self.lew23w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew23w3.setGeometry(QtCore.QRect(935, 431, 110, 29))
        self.lew23w3.setMaxLength(2)
        self.lew23w3.setObjectName("lew23w3")
        self.lew23w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew23w1.setGeometry(QtCore.QRect(703, 431, 110, 29))
        self.lew23w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew23w1.setMaxLength(2)
        self.lew23w1.setObjectName("lew23w1")
        self.labelWort23Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort23Index.setGeometry(QtCore.QRect(1051, 431, 40, 19))
        self.labelWort23Index.setObjectName("labelWort23Index")
        self.labelWort23 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort23.setGeometry(QtCore.QRect(1097, 431, 103, 19))
        self.labelWort23.setObjectName("labelWort23")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(641, 71, 56, 19))
        self.label_25.setObjectName("label_25")
        self.lew14w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew14w3.setGeometry(QtCore.QRect(935, 71, 110, 29))
        self.lew14w3.setMaxLength(2)
        self.lew14w3.setObjectName("lew14w3")
        self.lew14w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew14w1.setGeometry(QtCore.QRect(703, 71, 110, 29))
        self.lew14w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew14w1.setMaxLength(2)
        self.lew14w1.setObjectName("lew14w1")
        self.lew14w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew14w2.setGeometry(QtCore.QRect(819, 71, 110, 29))
        self.lew14w2.setMaxLength(2)
        self.lew14w2.setObjectName("lew14w2")
        self.labelWort14Index = QtWidgets.QLabel(self.centralwidget)
        self.labelWort14Index.setGeometry(QtCore.QRect(1051, 71, 40, 19))
        self.labelWort14Index.setObjectName("labelWort14Index")
        self.labelWort14 = QtWidgets.QLabel(self.centralwidget)
        self.labelWort14.setGeometry(QtCore.QRect(1097, 71, 103, 19))
        self.labelWort14.setObjectName("labelWort14")
        self.pBRandom = QtWidgets.QPushButton(self.centralwidget)
        self.pBRandom.setGeometry(QtCore.QRect(380, 610, 171, 41))
        self.pBRandom.setObjectName("pBRandom")
        self.textEditSeed = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSeed.setGeometry(QtCore.QRect(120, 520, 1081, 51))
        self.textEditSeed.setReadOnly(True)
        self.textEditSeed.setObjectName("textEditSeed")
        self.lew24w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lew24w1.setGeometry(QtCore.QRect(703, 470, 110, 29))
        self.lew24w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lew24w1.setMaxLength(2)
        self.lew24w1.setObjectName("lew24w1")
        self.pPBCreateHash = QtWidgets.QPushButton(self.centralwidget)
        self.pPBCreateHash.setGeometry(QtCore.QRect(570, 610, 171, 41))
        self.pPBCreateHash.setObjectName("pPBCreateHash")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lew1w1, self.lew1w2)
        MainWindow.setTabOrder(self.lew1w2, self.lew1w3)
        MainWindow.setTabOrder(self.lew1w3, self.lew2w1)
        MainWindow.setTabOrder(self.lew2w1, self.lew2w2)
        MainWindow.setTabOrder(self.lew2w2, self.lew2w3)
        MainWindow.setTabOrder(self.lew2w3, self.lew3w1)
        MainWindow.setTabOrder(self.lew3w1, self.lew3w2)
        MainWindow.setTabOrder(self.lew3w2, self.lew3w3)
        MainWindow.setTabOrder(self.lew3w3, self.lew4w1)
        MainWindow.setTabOrder(self.lew4w1, self.lew4w2)
        MainWindow.setTabOrder(self.lew4w2, self.lew4w3)
        MainWindow.setTabOrder(self.lew4w3, self.lew5w1)
        MainWindow.setTabOrder(self.lew5w1, self.lew5w2)
        MainWindow.setTabOrder(self.lew5w2, self.lew5w3)
        MainWindow.setTabOrder(self.lew5w3, self.lew6w1)
        MainWindow.setTabOrder(self.lew6w1, self.lew6w2)
        MainWindow.setTabOrder(self.lew6w2, self.lew6w3)
        MainWindow.setTabOrder(self.lew6w3, self.lew7w1)
        MainWindow.setTabOrder(self.lew7w1, self.lew7w2)
        MainWindow.setTabOrder(self.lew7w2, self.lew7w3)
        MainWindow.setTabOrder(self.lew7w3, self.lew8w1)
        MainWindow.setTabOrder(self.lew8w1, self.lew8w2)
        MainWindow.setTabOrder(self.lew8w2, self.lew8w3)
        MainWindow.setTabOrder(self.lew8w3, self.lew9w1)
        MainWindow.setTabOrder(self.lew9w1, self.lew9w2)
        MainWindow.setTabOrder(self.lew9w2, self.lew9w3)
        MainWindow.setTabOrder(self.lew9w3, self.lew10w1)
        MainWindow.setTabOrder(self.lew10w1, self.lew10w2)
        MainWindow.setTabOrder(self.lew10w2, self.lew10w3)
        MainWindow.setTabOrder(self.lew10w3, self.lew11w1)
        MainWindow.setTabOrder(self.lew11w1, self.lew11w2)
        MainWindow.setTabOrder(self.lew11w2, self.lew11w3)
        MainWindow.setTabOrder(self.lew11w3, self.lew12w1)
        MainWindow.setTabOrder(self.lew12w1, self.lew12w2)
        MainWindow.setTabOrder(self.lew12w2, self.lew12w3)
        MainWindow.setTabOrder(self.lew12w3, self.lew13w1)
        MainWindow.setTabOrder(self.lew13w1, self.lew13w2)
        MainWindow.setTabOrder(self.lew13w2, self.lew13w3)
        MainWindow.setTabOrder(self.lew13w3, self.lew14w1)
        MainWindow.setTabOrder(self.lew14w1, self.lew14w2)
        MainWindow.setTabOrder(self.lew14w2, self.lew14w3)
        MainWindow.setTabOrder(self.lew14w3, self.lew15w1)
        MainWindow.setTabOrder(self.lew15w1, self.lew15w2)
        MainWindow.setTabOrder(self.lew15w2, self.lew15w3)
        MainWindow.setTabOrder(self.lew15w3, self.lew16w1)
        MainWindow.setTabOrder(self.lew16w1, self.lew16w2)
        MainWindow.setTabOrder(self.lew16w2, self.lew16w3)
        MainWindow.setTabOrder(self.lew16w3, self.lew17w1)
        MainWindow.setTabOrder(self.lew17w1, self.lew17w2)
        MainWindow.setTabOrder(self.lew17w2, self.lew17w3)
        MainWindow.setTabOrder(self.lew17w3, self.lew18w1)
        MainWindow.setTabOrder(self.lew18w1, self.lew18w2)
        MainWindow.setTabOrder(self.lew18w2, self.lew18w3)
        MainWindow.setTabOrder(self.lew18w3, self.lew19w1)
        MainWindow.setTabOrder(self.lew19w1, self.lew19w2)
        MainWindow.setTabOrder(self.lew19w2, self.lew19w3)
        MainWindow.setTabOrder(self.lew19w3, self.lew20w1)
        MainWindow.setTabOrder(self.lew20w1, self.lew20w2)
        MainWindow.setTabOrder(self.lew20w2, self.lew20w3)
        MainWindow.setTabOrder(self.lew20w3, self.lew21w1)
        MainWindow.setTabOrder(self.lew21w1, self.lew21w2)
        MainWindow.setTabOrder(self.lew21w2, self.lew21w3)
        MainWindow.setTabOrder(self.lew21w3, self.lew22w1)
        MainWindow.setTabOrder(self.lew22w1, self.lew22w2)
        MainWindow.setTabOrder(self.lew22w2, self.lew22w3)
        MainWindow.setTabOrder(self.lew22w3, self.lew23w1)
        MainWindow.setTabOrder(self.lew23w1, self.lew23w2)
        MainWindow.setTabOrder(self.lew23w2, self.lew23w3)
        MainWindow.setTabOrder(self.lew23w3, self.lew24w1)
        MainWindow.setTabOrder(self.lew24w1, self.pBCalculate)
        MainWindow.setTabOrder(self.pBCalculate, self.pBClear)
        MainWindow.setTabOrder(self.pBClear, self.pBRandom)
        MainWindow.setTabOrder(self.pBRandom, self.pPBCreateHash)
        MainWindow.setTabOrder(self.pPBCreateHash, self.textEditSeed)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Seed würfeln", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Würfel 1-16", None, -1))
        self.pBCalculate.setText(QtWidgets.QApplication.translate("MainWindow", "calculate", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 1", None, -1))
        self.labelWort1.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort1Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort2Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 2", None, -1))
        self.labelWort2.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort3.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort3Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 3", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 11", None, -1))
        self.labelWort11Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort11.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort6.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 6", None, -1))
        self.labelWort6Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort10.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 10", None, -1))
        self.labelWort10Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 8", None, -1))
        self.labelWort8Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort8.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort4Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort4.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 4", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 5", None, -1))
        self.labelWort5.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort5Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 12", None, -1))
        self.labelWort12Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort12.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.labelWort9Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort9.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 9", None, -1))
        self.labelWort7Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort7.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 7", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Seed", None, -1))
        self.pBClear.setText(QtWidgets.QApplication.translate("MainWindow", "löschen", None, -1))
        self.labelWort24.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 24", None, -1))
        self.labelWort24Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 13", None, -1))
        self.labelWort13Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort13.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 15", None, -1))
        self.labelWort15Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort15.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 16", None, -1))
        self.labelWort16Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort16.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 22", None, -1))
        self.labelWort22Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort22.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 21", None, -1))
        self.labelWort21Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort21.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 20", None, -1))
        self.labelWort20Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort20.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 17", None, -1))
        self.labelWort17Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort17.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 18", None, -1))
        self.labelWort18Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort18.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 19", None, -1))
        self.labelWort19Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort19.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 23", None, -1))
        self.labelWort23Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort23.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Wort 14", None, -1))
        self.labelWort14Index.setText(QtWidgets.QApplication.translate("MainWindow", "index", None, -1))
        self.labelWort14.setText(QtWidgets.QApplication.translate("MainWindow", "Ergebnis Wort", None, -1))
        self.pBRandom.setText(QtWidgets.QApplication.translate("MainWindow", "Zufall, simpel", None, -1))
        self.pPBCreateHash.setText(QtWidgets.QApplication.translate("MainWindow", "Create Hash", None, -1))

